name: Tests

# on:
#   push:
#     branches:
#       - master
#       - main
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '12'
#       - run: yarn install --frozen-lockfile
#       - run: yarn test
#       - run: yarn lint